import {
  BookOpenText,
  Activity,
  BrainCircuit,
  Building2,
  CalendarDays,
  FolderKanban,
  ImageIcon,
  HeartPulse,
  CreditCard,
  LayoutDashboard,
  Mail,
  UsersRound,
  Settings2,
  Sparkles,
  Wrench,
  TrendingUp,
  Languages,
  Store,
  Blocks,
  ShieldCheck,
} from 'lucide-react';

export const adminNavigationItems = [
  { href: '/admin/dashboard', icon: LayoutDashboard, label: '概览' },
  { href: '/admin/analytics', icon: Activity, label: '分析' },
  { href: '/admin/system', icon: HeartPulse, label: '系统状态' },
  { href: '/admin/growth', icon: TrendingUp, label: '增长' },
  { href: '/admin/content-plan', icon: CalendarDays, label: '内容计划' },
  { href: '/admin/projects', icon: FolderKanban, label: '项目' },
  { href: '/admin/blog', icon: BookOpenText, label: '文章' },
  { href: '/admin/services', icon: Wrench, label: '服务' },
  { href: '/admin/translations', icon: Languages, label: '翻译' },
  { href: '/admin/messages', icon: Mail, label: '咨询' },
  { href: '/admin/crm/dashboard', icon: UsersRound, label: 'CRM' },
  { href: '/admin/saas', icon: Building2, label: 'SaaS' },
  { href: '/admin/enterprise', icon: ShieldCheck, label: '企业安全' },
  { href: '/admin/security/audit', icon: ShieldCheck, label: '企业审计' },
  { href: '/admin/business', icon: TrendingUp, label: '商业数据' },
  { href: '/admin/billing', icon: CreditCard, label: '账单运营' },
  { href: '/admin/ai', icon: Sparkles, label: 'AI Center' },
  { href: '/admin/ai-platform', icon: BrainCircuit, label: 'AI 平台运营' },
  { href: '/admin/ai-governance', icon: ShieldCheck, label: 'AI 企业治理' },
  { href: '/admin/apps', icon: Blocks, label: 'AI 应用' },
  { href: '/admin/marketplace', icon: Store, label: 'Marketplace' },
  { href: '/admin/knowledge', icon: BrainCircuit, label: 'AI 知识' },
  { href: '/admin/media', icon: ImageIcon, label: '媒体库' },
  { href: '/admin/settings', icon: Settings2, label: '设置' },
] as const;
